version: '3'

services:
  build-cache:
    build:
      context: .
      dockerfile: ./build-cache.Dockerfile
    image: maxmcd/deno:_build-cache
  build-cache-jessie:
    build:
      context: .
      dockerfile: ./build-cache-jessie.Dockerfile
    image: maxmcd/deno:_build-cache-jessie
  deno:
    build: 
      context: .
      dockerfile: ./Dockerfile
    image: maxmcd/deno:master
  slim-jessie:
    build:
      context: .
      dockerfile: ./slim-jessie.Dockerfile
    image: maxmcd/deno:slim-jessie
  slim:
    build:
      context: .
      dockerfile: ./slim.Dockerfile
    image: maxmcd/deno:slim
