version: '3.2'

services:
  build-cache:
    build:
      context: .
      dockerfile: ./build-cache.Dockerfile
    image: maxmcd/deno:_build-cache
  master:
    build: 
      context: .
      dockerfile: ./Dockerfile
    image: maxmcd/deno:master
  jessie:
    build: 
      context: ./0/jessie/
      dockerfile: Dockerfile
      args:
        DENO_VERSION: 0.2.4
    image: maxmcd/deno:jessie
  slim:
    build: 
      context: ./0/slim/
      dockerfile: Dockerfile
      args:
        DENO_VERSION: 0.2.4
    image: maxmcd/deno:slim
