version: '3.2'

services:
  build-cache:
    build:
      context: .
      dockerfile: ./build-cache.Dockerfile
    image: maxmcd/deno:_build-cache
  master:
    build: 
      context: .
      dockerfile: ./Dockerfile
    image: maxmcd/deno:master
  jessie:
    build: ./0/jessie/
    image: maxmcd/deno:jessie
  slim:
    build: ./0/slim/
    image: maxmcd/deno:slim
