service: gcf-nodejs

provider:
  name: google
  runtime: nodejs
  project: media-9x16
  # the path to the credentials file needs to be absolute
  credentials: ~/.gcloud/keyfile.json


package:
 include:
   - ./**

 functions:
   first:
     handler: http
     events:
       - http: path
